USE MFG_Solutions
GO

IF OBJECT_ID (N'VM2F_BDU_Class_DFFS_Explanatory', N'U') IS NOT NULL
	DROP TABLE [VM2F_BDU_Class_DFFS_Explanatory];

IF OBJECT_ID (N'VM2F_BDU_Class_DFFS_Target', N'U') IS NOT NULL
	DROP TABLE [VM2F_BDU_Class_DFFS_Target];

IF OBJECT_ID (N'VM2F_BDU_Class_DFFS_Prediction', N'U') IS NOT NULL
	DROP TABLE [VM2F_BDU_Class_DFFS_Prediction];

CREATE TABLE VM2F_BDU_Class_DFFS_Explanatory (ID INT, TestName VARCHAR(MAX))

CREATE TABLE VM2F_BDU_Class_DFFS_Target (ID INT, TestName VARCHAR(MAX), Resolution FLOAT)

CREATE TABLE VM2F_BDU_Class_DFFS_Prediction (ID INT, TestName VARCHAR(MAX))

INSERT INTO VM2F_BDU_Class_DFFS_Explanatory VALUES 