USE [master]
GO

/****** Object:  Database [MFG_Solutions]    Script Date: 6/16/2014 3:25:46 PM ******/

IF EXISTS(select 1 from sys.databases where name='MFG_Solutions')
	DROP DATABASE [MFG_Solutions]
GO

/****** Object:  Database [MFG_Solutions]    Script Date: 6/16/2014 3:25:46 PM ******/
CREATE DATABASE [MFG_Solutions]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MFG_Solutions', FILENAME = N'F:\MSSQL11.SQL01\MSSQL\DATA\MFG_Solutions.mdf' , SIZE = 51200KB , MAXSIZE = UNLIMITED, FILEGROWTH = 25%), 
 FILEGROUP [SolutionID_FG1] 
( NAME = N'MFG_1', FILENAME = N'F:\MSSQL11.SQL01\MSSQL\DATA\MFG_1.ndf' , SIZE = 51200KB , MAXSIZE = UNLIMITED, FILEGROWTH = 25%), 
 FILEGROUP [SolutionID_FG10] 
( NAME = N'MFG_10', FILENAME = N'F:\MSSQL11.SQL01\MSSQL\DATA\MFG_10.ndf' , SIZE = 51200KB , MAXSIZE = UNLIMITED, FILEGROWTH = 25%), 
 FILEGROUP [SolutionID_FG2] 
( NAME = N'MFG_2', FILENAME = N'F:\MSSQL11.SQL01\MSSQL\DATA\MFG_2.ndf' , SIZE = 51200KB , MAXSIZE = UNLIMITED, FILEGROWTH = 25%), 
 FILEGROUP [SolutionID_FG3] 
( NAME = N'MFG_3', FILENAME = N'F:\MSSQL11.SQL01\MSSQL\DATA\MFG_3.ndf' , SIZE = 51200KB , MAXSIZE = UNLIMITED, FILEGROWTH = 25%), 
 FILEGROUP [SolutionID_FG4] 
( NAME = N'MFG_4', FILENAME = N'F:\MSSQL11.SQL01\MSSQL\DATA\MFG_4.ndf' , SIZE = 51200KB , MAXSIZE = UNLIMITED, FILEGROWTH = 25%), 
 FILEGROUP [SolutionID_FG5] 
( NAME = N'MFG_5', FILENAME = N'F:\MSSQL11.SQL01\MSSQL\DATA\MFG_5.ndf' , SIZE = 51200KB , MAXSIZE = UNLIMITED, FILEGROWTH = 25%), 
 FILEGROUP [SolutionID_FG6] 
( NAME = N'MFG_6', FILENAME = N'F:\MSSQL11.SQL01\MSSQL\DATA\MFG_6.ndf' , SIZE = 51200KB , MAXSIZE = UNLIMITED, FILEGROWTH = 25%), 
 FILEGROUP [SolutionID_FG7] 
( NAME = N'MFG_7', FILENAME = N'F:\MSSQL11.SQL01\MSSQL\DATA\MFG_7.ndf' , SIZE = 51200KB , MAXSIZE = UNLIMITED, FILEGROWTH = 25%), 
 FILEGROUP [SolutionID_FG8] 
( NAME = N'MFG_8', FILENAME = N'F:\MSSQL11.SQL01\MSSQL\DATA\MFG_8.ndf' , SIZE = 51200KB , MAXSIZE = UNLIMITED, FILEGROWTH = 25%), 
 FILEGROUP [SolutionID_FG9] 
( NAME = N'MFG_9', FILENAME = N'F:\MSSQL11.SQL01\MSSQL\DATA\MFG_9.ndf' , SIZE = 51200KB , MAXSIZE = UNLIMITED, FILEGROWTH = 25%)
 LOG ON 
( NAME = N'MFG_Solutions_log', FILENAME = N'F:\MSSQL11.SQL01\MSSQL\DATA\MFG_Solutions_log.ldf' , SIZE = 40000KB , MAXSIZE = 2048GB , FILEGROWTH = 25%)
GO

ALTER DATABASE [MFG_Solutions] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MFG_Solutions].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MFG_Solutions] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MFG_Solutions] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MFG_Solutions] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MFG_Solutions] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MFG_Solutions] SET ARITHABORT OFF 
GO

ALTER DATABASE [MFG_Solutions] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MFG_Solutions] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [MFG_Solutions] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MFG_Solutions] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MFG_Solutions] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MFG_Solutions] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MFG_Solutions] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MFG_Solutions] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MFG_Solutions] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MFG_Solutions] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MFG_Solutions] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MFG_Solutions] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MFG_Solutions] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MFG_Solutions] SET TRUSTWORTHY ON 
GO

ALTER DATABASE [MFG_Solutions] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MFG_Solutions] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MFG_Solutions] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MFG_Solutions] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MFG_Solutions] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [MFG_Solutions] SET  MULTI_USER 
GO

ALTER DATABASE [MFG_Solutions] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MFG_Solutions] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MFG_Solutions] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MFG_Solutions] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [MFG_Solutions] SET  READ_WRITE 
GO

--Permissions
USE [MFG_Solutions]
GO
CREATE USER [AMR\ADVBI_PROD_PAP_Developer] FOR LOGIN [AMR\ADVBI_PROD_PAP_Developer]
GO
USE [MFG_Solutions]
GO
ALTER ROLE [db_datareader] ADD MEMBER [AMR\ADVBI_PROD_PAP_Developer]
GO
